greeting:
  addressing: "Hi"

quarkus:
  datasource:
    devservices:
      port: 5432
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
    schema-management:
      strategy: validate
  liquibase:
    change-log: db/changelog/db.changelog.yaml
    migrate-at-start: true
