-- This file allow to write SQL commands that will be emitted in test and dev.
-- The commands are commented as their support depends of the database
-- insert into greeting_entity (id, greeting) values(1, 'How are you?');
